import turtle
import math

turtle.forward(10)
turtle.penup()
turtle.forward(10)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(10)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(10)
turtle.pendown()
turtle.forward(10)
turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(10)
turtle.penup()
turtle.forward(10)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(10)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(10)
turtle.pendown()
turtle.forward(10)
turtle.left(90)
turtle.forward(90)
turtle.left(135)
turtle.forward (math.sqrt((90**2)*2))
turtle.left(225)
turtle.forward(90)
turtle.left(225)
turtle.forward (math.sqrt((90**2)*2))


input('press any key to exit')